#!/usr/bin/env python3
"""memory_sync.py -- global agent-ops automation (owned by this repo).

Bidirectional daily sync of Claude Code's file-based memory, a workaround for
the auto-memory the CLI writes regardless of instruction. Two directions:

  CAPTURE  native memory files -> $BRAIN_DB/raw/agent-memory/<host>/ (a per-host
           backup + signal for the session-learnings pass). Per-project memory is
           FIRST-CLASS, human-curated (real frontmatter + a curated MEMORY.md
           index) -- it is captured and LEFT IN PLACE, NEVER deleted. The shared
           canonical slot is likewise captured but not deleted.

  RESTORE  the CANONICAL memory ($BRAIN_DB/memory/MEMORY.md, the tracked source
           of truth) -> the native memory slot Claude reads at session start, so
           the next session reads the curated file rather than the day's drift.
           This machine's LOCAL CAPABILITIES.md (generated by index_capabilities,
           gitignored, never pushed) is restored into the slot alongside it.

The native slot is Claude Code's auto-memory dir. With `autoMemoryDirectory` set
(e.g. the Mac) all projects share one global dir (env AUTO_MEMORY_DIR here,
default ~/.claude/memory); without it (a per-project-memory machine) each project
keeps its own curated ~/.claude[/<cfg>]/projects/*/memory/ that Claude reads for
that project. Both are backed up and PRESERVED -- this job never deletes memory.

Config (env): BRAIN_DB (default ~/Claude/brain-db); AUTO_MEMORY_DIR (default
~/.claude/memory). Extra config roots one per line in agent-ops/session-roots.local.
"""
import os, sys, glob, shutil, socket, datetime, pathlib

HOME = pathlib.Path.home()
BRAIN_DB = pathlib.Path(os.environ.get("BRAIN_DB", HOME / "Claude" / "brain-db"))
HOST = socket.gethostname().split(".")[0]
RAW_DIR = pathlib.Path(os.environ.get("MEMORY_RAW", BRAIN_DB / "raw" / "agent-memory")) / HOST
CANONICAL = BRAIN_DB / "memory" / "MEMORY.md"
AUTO_MEMORY_DIR = pathlib.Path(os.environ.get("AUTO_MEMORY_DIR", HOME / ".claude" / "memory"))
HERE = pathlib.Path(__file__).resolve().parent
ROOTS_FILE = HERE / "session-roots.local"


def config_roots():
    roots = [HOME / ".claude"]
    if ROOTS_FILE.exists():
        for line in ROOTS_FILE.read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                p = pathlib.Path(os.path.expanduser(line))
                if p.exists():
                    roots.append(p)
    return roots


def capture_one(mf, project, delete):
    """Copy a native memory file into the store; delete native if requested and
    the copy verifies. Returns (captured, deleted)."""
    today = datetime.date.today().isoformat()
    try:
        content = mf.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        print(f"  WARN unreadable {mf}: {e}", file=sys.stderr)
        return 0, 0
    front = (
        "---\n"
        "source: agent-memory\n"
        f"host: {HOST}\n"
        f"project: {project}\n"
        f"native_file: {mf}\n"
        f"captured: {today}\n"
        "contexts: operating\n"
        "---\n\n"
    )
    payload = front + content + ("" if content.endswith("\n") else "\n")
    out = RAW_DIR / f"{today}__{project}__{mf.name}"
    out.write_text(payload, encoding="utf-8")
    verified = out.exists() and out.read_text(encoding="utf-8") == payload
    if delete and verified:
        try:
            mf.unlink(); return 1, 1
        except Exception as e:
            print(f"  WARN could not remove {mf}: {e}", file=sys.stderr)
    return (1 if verified else 0), 0


def slot_is_read():
    """True iff this machine's Claude Code reads AUTO_MEMORY_DIR at session start
    -- i.e. an effective `autoMemoryDirectory` setting resolves to it AND
    auto-memory is not disabled. On a per-project-memory machine (setting absent)
    this is False: restoring into the slot would write a dir nothing reads. There,
    global memory is delivered by a CLAUDE.md @import of the brain-db canonical
    instead (see the memory-sync design)."""
    import json
    val = None
    enabled = True
    for cfg in (HOME / ".claude" / "settings.json",
                HOME / ".claude" / "settings.local.json"):   # local overrides base
        try:
            data = json.loads(cfg.read_text(encoding="utf-8"))
        except Exception:
            continue
        if not isinstance(data, dict):
            continue
        if data.get("autoMemoryDirectory"):
            val = data["autoMemoryDirectory"]
        if "autoMemoryEnabled" in data:
            enabled = data["autoMemoryEnabled"]
    # A dir set but auto-memory explicitly disabled means the slot is unread.
    if not val or enabled is False:
        return False
    try:
        return pathlib.Path(os.path.expanduser(val)).resolve() == AUTO_MEMORY_DIR.resolve()
    except Exception:
        return False


def main():
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    captured = deleted = 0

    # CAPTURE: the shared canonical slot (keep it), then per-project curated
    # memory. Per-project memory is first-class -- back it up per host and LEAVE
    # IT IN PLACE (delete=False); this job never sweeps curated memory.
    # CAPABILITIES.md is a machine-DERIVED artifact restored into the slot below,
    # not real agent memory -- never capture it into the store.
    if AUTO_MEMORY_DIR.exists():
        for mf in sorted(AUTO_MEMORY_DIR.glob("*.md")):
            if mf.name == "CAPABILITIES.md":
                continue
            c, d = capture_one(mf, "_canonical-slot", delete=False)
            captured += c; deleted += d
    for root in config_roots():
        for mf in sorted(glob.glob(str(root / "projects" / "*" / "memory" / "*.md"))):
            mf = pathlib.Path(mf)
            project = mf.parent.parent.name.lstrip("-")
            if project.endswith("-worktree"):
                continue          # transient worktree session, not a real project
            c, d = capture_one(mf, project, delete=False)
            captured += c; deleted += d

    # RESTORE: canonical -> the native slot, plus this machine's LOCAL
    # capabilities catalog alongside it (read-only local copies; neither pushed).
    # ONLY on a machine that actually reads the slot (autoMemoryDirectory resolves
    # to it). On a per-project-memory machine the slot is unread, so writing it
    # would be misleading -- global memory there arrives via a CLAUDE.md @import
    # of the brain-db canonical instead.
    restored = False
    if not slot_is_read():
        print(f"  RESTORE skipped: autoMemoryDirectory does not resolve to "
              f"{AUTO_MEMORY_DIR} (per-project machine; global memory loads via "
              f"CLAUDE.md @import)")
    elif CANONICAL.exists():
        AUTO_MEMORY_DIR.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(CANONICAL, AUTO_MEMORY_DIR / "MEMORY.md")
        restored = True
        caps = BRAIN_DB / "memory" / "CAPABILITIES.md"
        if caps.exists():
            shutil.copyfile(caps, AUTO_MEMORY_DIR / "CAPABILITIES.md")
    else:
        print(f"  WARN no canonical memory at {CANONICAL} -- nothing to restore", file=sys.stderr)

    # Commit ONLY the captured raw agent-memory (host-scoped, additive) so nothing
    # is left dirty for the next job. The capabilities index is machine-derived,
    # local, and gitignored -- it is NEVER staged, committed, or pushed (a shared
    # index diverges across machines). memory/ is deliberately excluded here.
    import subprocess
    try:
        subprocess.run(["git", "-C", str(BRAIN_DB), "add", "raw/agent-memory"],
                       check=False)
        dirty = subprocess.run(["git", "-C", str(BRAIN_DB), "status", "--porcelain",
                                "raw/agent-memory"],
                               capture_output=True, text=True).stdout.strip()
        if dirty:
            subprocess.run(["git", "-C", str(BRAIN_DB), "commit", "-q", "-m",
                            f"memory: nightly agent-memory capture ({HOST})"], check=False)
            subprocess.run(["git", "-C", str(BRAIN_DB), "push", "-q", "origin", "main"],
                           check=False)
            print("  brain-db: committed + pushed agent-memory capture")
    except Exception as e:
        print(f"  WARN brain-db commit skipped: {e}")

    print(f"memory-sync[{HOST}]: captured={captured} swept={deleted} "
          f"restored={'yes' if restored else 'no'} -> {AUTO_MEMORY_DIR}/MEMORY.md")


if __name__ == "__main__":
    main()
